# Copyright (C) 2016  Stephan Kreutzer
# Creative Commons BY-SA 4.0
# http://www.refugee-it.de



directories = ./1 ./2 ./3 ./4 ./5 ./6 ./7 ./8



.PHONY: all $(directories)



all: $(directories)



$(directories):
	$(MAKE) --directory=$@
