# Copyright (C) 2016  Stephan Kreutzer
# GNU Affero General Public License 3 or, at your option, any later version of this license.
# http://www.refugee-it.de



directories = ./1 ./2 ./3 ./4 ./5 ./6 ./7 ./8



.PHONY: all $(directories)



all: $(directories)



$(directories):
	$(MAKE) --directory=$@
